use tableauconnect;

create or replace view Dataset1_v as 
select `countries`.`country_id`,
    `countries`.`country_name`,
    `countries`.`region`,
    `categories`.`cat_id`,
    -- `categories`.`country_id`,
    `categories`.`name`,
    `categories`.`decay_rate`,
    `categories`.`ceiling_L`,
    `categories`.`ceiling_C`,
    `categories`.`ceiling_S`,
    `categories`.`ceiling_O`,
    `categories`.`decay_speed`,
    `categories`.`competitor_hit_L`,
    `categories`.`competitor_hit_C`,
    `categories`.`competitor_hit_S`,
    `categories`.`competitor_hit_O`,
    `categories`.`non_tv_effectiveness`,
    `realcategory_fv`.`year`,
    -- `realcategory_fv`.`cat_id`,
    -- `realcategory_fv`.`country_id`,
    `realcategory_fv`.`market_size`,
    `realcategory_fv`.`market_share_UL`,
    `realcategory_fv`.`growth_2y`,
    `realcategory_fv`.`growth_5y`,
    `realcategory_fv`.`media_spending_all`,
    `realcategory_fv`.`incremental_usage`,
    `realcategory_fv`.`conviction_cat`,
    `brands`.`brand_id`,
    `brands`.`name` brand_name,
    `brands`.`local_name`,
    `brands`.`is_UL`,
    `brands`.`brand_status`,
    -- `brands`.`cat_id`,
    --	`realbrand_fv`.`brand_id`,
    -- `realbrand_fv`.`cat_id`,
    -- `realbrand_fv`.`country_id`,
    -- `realbrand_fv`.`year`,
    `realbrand_fv`.`turnover`,
    `realbrand_fv`.`gross_margin`,
    `realbrand_fv`.`tv_.`,
    `realbrand_fv`.`spending`,
    `realbrand_fv`.`grp_cost`,
    `realbrand_fv`.`share_of_value`,
    `realbrand_fv`.`growth`,
    `realbrand_fv`.`how_many`,
    `realbrand_fv`.`conviction`,
    `realbrand_fv`.`ai`,
    `realbrand_fv`.`ai2c`,
    -- `estimatedbrand_fv`.`brand_id`,
    -- `estimatedbrand_fv`.`year`,
    `estimatedbrand_fv`.`to_return`,
    `estimatedbrand_fv`.`gp_return`,
    `estimatedbrand_fv`.`protected_fraction`,
    `estimatedbrand_fv`.`gained_fraction`,
    `estimatedbrand_fv`.`total_cut_through`,
    `estimatedbrand_fv`.`tv_cut_trough`,
    `estimatedbrand_fv`.`conviction_growth_factor`,
    `estimatedbrand_fv`.`decay`,
    `estimatedbrand_fv`.`conviction_gain`,
    `estimatedbrand_fv`.`fair_share`,
    `estimatedbrand_fv`.`conviction_lost`,
    `estimatedbrand_fv`.`ceiling`,
    `estimatedbrand_fv`.`competitor_hit`
  from countries,
	   categories,
       RealCategory_Fv,
       brands,
       RealBrand_Fv
       ,EstimatedBrand_Fv
 where categories.country_id = countries.country_id
   and RealCategory_Fv.cat_id = categories.cat_id
   and brands.cat_id = categories.cat_id
   and RealBrand_Fv.brand_id = brands.brand_id
   and RealBrand_Fv.year = realcategory_fv.year
   and EstimatedBrand_Fv.brand_id = realbrand_fv.brand_id
   and EstimatedBrand_Fv.year = realbrand_fv.year